# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

#Pipeline -> Stages - > Jobs (which was called as "Task")

jobs:
- job: TestJob01
  steps:
  - script: echo Hello, Nadeem Siddiqui - This is TestJob01!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: TestJob02
  dependsOn: TestJob01
  steps:
  - script: echo Hello, Nadeem Siddiqui - This is TestJob02!
    displayName: 'Run a one-line script'

- job: TestJob03
  dependsOn: TestJob01
  steps:
  - script: echo Hello, Nadeem Siddiqui - This is TestJob02!
    displayName: 'Run a one-line script'

- job: TestJob04
  dependsOn: 
    TestJob02
    TestJob03
  steps:
  - script: echo Hello, Nadeem Siddiqui - This is TestJob02!
    displayName: 'Run a one-line script'

