# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildFirstJob
    steps:
    - bash: echo BuildFirstJob!
    - bash: echo $(PipelineLevel)
      displayName: 'Run a one-line script'
  - job: BuildSecoundJob
    steps:
    - bash: echo BuildSecoundJob!
      displayName: 'Run a one-line script'
- stage: Dev
  variables:
   environment: Dev
  dependsOn: Build
  jobs:
  - job: DevFirstJob
    steps:
    - bash: echo $(environment)FirstJob!
      displayName: 'Run a one-line script'
- stage: QA
  variables:
   environment: QA
  dependsOn: Build
  jobs:
  - job: QAFirstJob
    steps:
    - bash: echo $(environment)FirstJob!
      displayName: 'Run a one-line script'
- stage: Prod
  variables:
   environment: Prod
  dependsOn: 
  - Dev
  - QA
  jobs:
  - job: ProdFirstJob
    steps:
    - bash: echo $(environment)irstJob!
      displayName: 'Run a one-line script'






