
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
   - job: BuildJob
     steps:
     - bash: echo "Do This"
- stage: DevDeploy
  jobs:
  - deployment: DevDeploymentJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: DevDeploymentJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Deploy to QA






